export const tagDescriptions: Record<string, string> = {
  JavaScript: "Dynamic scripting language for web development",
  TypeScript: "Typed superset of JavaScript for scalable apps",
  React: "UI library for building component-based interfaces",
  "Next.js": "React framework for production applications",
  "Tailwind CSS": "Utility-first CSS framework for rapid styling",
  "Redux Toolkit": "Official Redux toolset for state management",
  PrimeReact: "Rich UI component suite for React",
  "Feature-Sliced Design": "Architectural methodology for frontend",
  Redux: "Predictable state container for JavaScript apps",
  "styled-components": "CSS-in-JS library for React components",
  "React Hook Form": "Performant forms with easy validation",
  "Chakra UI": "Accessible component library for React",
  "Material UI": "React components following Material Design",
  Axios: "Promise-based HTTP client for the browser",
  Motion: "Production-ready animation library for React",
  "TanStack Query": "Async state management for data fetching",
  "View on Github": "View source code on GitHub",
};
